name: Commodities Trade Application

services:
  data_extraction:
    build:
      context: ./data_extraction
      dockerfile: Dockerfile
    image: commodities_extraction
    container_name: commodities_trade_app
    volumes:
      - commodities_trade_app:/commodities_datasets
    command: ["python", "data_extraction.py"]

  commodities_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: commodities_app
    depends_on:
      - data_extraction
    volumes:
      - commodities_trade_app:/commodities_datasets
    ports:
      - "8501:8501"

volumes:
  commodities_trade_app:


